### ISSUE TITLE
Create Phase 3 strategy planning roadmap

### ISSUE THREAD

**Issue by bhuvanshri** [MozillaFoundation/strategy#47]
- [x] First draft to be created by @OpenMatt 
- [x] To be refined between @bhuvanshri and @OpenMatt 
- [x] Get agreement of Mark, Angela, Chris and David
- [x] Execute!
